### ISSUE TITLE
on ChangeValue for Supplier when trying to add a new product.

### ISSUE THREAD

**Issue by aralco** [aralco/acredito#2]
Jul 05, 2015 9:35:46 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.lang.IllegalArgumentException: The attribute [fullName] from the managed type [EntityTypeImpl@1088153449:Supplier [ javaType: class com.bo.acredito.domain.Supplier descriptor: RelationalDescriptor(com.bo.acredito.domain.Supplier --> [DatabaseTable(SUPPLIER)]), mappings: 10]] is not present.
	at org.eclipse.persistence.internal.jpa.metamodel.ManagedTypeImpl.getAttribute(ManagedTypeImpl.java:148)
	at org.eclipse.persistence.internal.jpa.querydef.FromImpl.get(FromImpl.java:312)
	at com.vaadin.addon.jpacontainer.filter.util.AdvancedFilterableSupport.getPropertyPathTyped(AdvancedFilterableSupport.java:242)
	at com.vaadin.addon.jpacontainer.filter.util.AdvancedFilterableSupport.getPropertyPath(AdvancedFilterableSupport.java:235)
	at com.vaadin.addon.jpacontainer.filter.util.FilterConverter$SimpleStringFilterConverter.toPredicate(FilterConverter.java:167)
	at com.vaadin.addon.jpacontainer.filter.util.FilterConverter.convertFilter(FilterConverter.java:278)
	at com.vaadin.addon.jpacontainer.provider.LocalEntityProvider.doGetEntityCount(LocalEntityProvider.java:518)
	at com.vaadin.addon.jpacontainer.provider.CachingSupport$FilterCacheEntry.getEntityCount(CachingSupport.java:157)
	at com.vaadin.addon.jpacontainer.provider.CachingSupport.getEntityCount(CachingSupport.java:826)
	at com.vaadin.addon.jpacontainer.provider.CachingMutableLocalEntityProvider.getEntityCount(CachingMutableLocalEntityProvider.java:130)
	at com.vaadin.addon.jpacontainer.JPAContainer.size(JPAContainer.java:912)
	at com.vaadin.ui.ComboBox.getOptionsWithFilter(ComboBox.java:387)
	at com.vaadin.ui.ComboBox.paintContent(ComboBox.java:217)
	at com.vaadin.server.LegacyPaint.paint(LegacyPaint.java:65)
	at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:81)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:106)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:149)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:97)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1382)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:45)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by asejas** [comment]
Fixed on SHA: cb1f32c75b299df25b95c7109520330096b705aa
Transient fields removed to avoid problem
